[package]
name = "marccheck"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/sts10/marccheck"

[dependencies]
clap = { version = "4.5.58", features = ["derive"] }

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
